<!DOCTYPE html>
<html>
<head>
  <title>BBQ Invitation</title>
</head>
<body style="font-family: Arial, sans-serif; background-color: #fdf6e3; color: #333; padding: 20px;">
  <h2>Hey neighbors! 👋</h2>
  <p>We're firing up the grill this <strong>Saturday at 4 PM</strong> and would love for you to join us for a backyard barbecue!</p>
  <p>There’ll be good food, cold drinks, and great company. Bring whatever you’d like to throw on the grill, a side or drink to share if you’d like, and any friends or family who are around.</p>
  <p>It’ll be at our place — just follow the delicious smell of barbecue! Let us know if you can make it. Hope to see you there!</p>
  <p>Cheers,<br>
  <em>[Your Name / Your Family’s Name]</em></p>
</body>
</html>
